### ISSUE TITLE
Missing dependency `systemfonts`

### ISSUE THREAD

**Issue by mezarque** [Arcadia-Science/arcadiathemeR#26]
Using a fresh installation of R and Rstudio, I installed `arcadiathemeR` using the `remotes` package. After doing so, I received an error when trying to run the example code below:

```R
library(ggplot2)
library(arcadiathemeR)

ggplot(data=mtcars, aes(x=hp, y=mpg, color=as.factor(cyl))) + geom_point(size=2.5) + theme_arcadia(x_axis_type = "numerical") + scale_color_arcadia(palette_name = "primary")
```

Error:
```
Error in loadNamespace(x) : there is no package called ‘systemfonts’
```

Does the package handle its own dependencies when installed using `remotes::install_github("Arcadia-Science/arcadiathemeR")`? If so, we should make sure that `systemfonts` is included in that list of dependencies.

**Comment by elizabethmcd** [comment]
fixed in latest PR
